name: Build and deploy WAR app to Virtual Machine

env:
  JAVA_VERSION: '17'
  SQL_CONSTR: ${{ secrets.SQLAZURECONNSTR_WEB_APP_DB }}
  JAVA_APP: "Lab1.war"
  TEST_VARIABLE: "TEST_VALUE"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'


      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: workdir

      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: workdir/${{ env.JAVA_APP }}
          remote: action/java-app.war
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Run a script on remote server (start the application)
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd action/
            set SQLAZURECONNSTR_WEB_APP_DB=${{ env.SQL_CONSTR }}
            set TEST=${{ env.TEST_VARIABLE }}
            java -jar java-app.war &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"
